# Generated by Django 2.2.4 on 2019-10-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RatePlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_price', models.IntegerField(verbose_name='ペット代金')),
                ('category', models.CharField(choices=[('0', '小型犬'), ('1', '中型犬'), ('2', '大型犬'), ('3', '猫')], default='0', max_length=1, verbose_name='種別')),
                ('dc_plan', models.CharField(choices=[('0', 'なし'), ('1', '1vac'), ('2', '2vac'), ('3', '3vac')], default='1', max_length=1, verbose_name='ドクターズチェックP')),
                ('hs_plan', models.CharField(choices=[('0', '未加入'), ('1', 'プラチナ年払い'), ('2', 'スタンダード年払い'), ('3', 'プラチナ月払い'), ('4', 'スタンダード月払い')], default='0', max_length=1, verbose_name='ほっとサポート')),
                ('insurance_plan', models.CharField(choices=[('0', '未加入'), ('1', '100%年払い'), ('2', '70%年払い'), ('3', '100%月払い'), ('4', '70%月払い')], default='0', max_length=1, verbose_name='ペット保険')),
                ('insurance_descount', models.BooleanField(default=False, verbose_name='保険多頭割')),
                ('food_plan', models.CharField(choices=[('0', 'なし'), ('1', 'あり')], default='0', max_length=1, verbose_name='ごはんセット')),
                ('home_plan', models.CharField(choices=[('0', 'なし'), ('1', 'サークル無しセット'), ('2', 'サークルセット（小）'), ('3', 'サークルセット（大）')], default='0', max_length=1, verbose_name='おうちセット')),
                ('care_plan', models.CharField(choices=[('0', 'なし'), ('1', '短毛用'), ('2', '長毛用')], default='0', max_length=1, verbose_name='しつけお手入れセット')),
            ],
        ),
    ]
