# Generated by Django 2.2.4 on 2019-10-03 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rateplan',
            name='category',
            field=models.IntegerField(choices=[(0, '小型犬'), (1, '中型犬'), (2, '大型犬'), (3, '猫')], default=0, verbose_name='種別'),
        ),
    ]
