# Generated by Django 2.2.4 on 2019-10-03 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191003_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rateplan',
            name='care_plan',
            field=models.IntegerField(choices=[('0', 'なし'), ('1', '短毛用'), ('2', '長毛用')], default=0, verbose_name='しつけお手入れセット'),
        ),
        migrations.AlterField(
            model_name='rateplan',
            name='dc_plan',
            field=models.IntegerField(choices=[('0', 'なし'), ('1', '1vac'), ('2', '2vac'), ('3', '3vac')], default=1, verbose_name='ドクターズチェックP'),
        ),
        migrations.AlterField(
            model_name='rateplan',
            name='food_plan',
            field=models.IntegerField(choices=[('0', 'なし'), ('1', 'あり')], default=0, verbose_name='ごはんセット'),
        ),
        migrations.AlterField(
            model_name='rateplan',
            name='home_plan',
            field=models.IntegerField(choices=[('0', 'なし'), ('1', 'サークル無しセット'), ('2', 'サークルセット（小）'), ('3', 'サークルセット（大）')], default=0, verbose_name='おうちセット'),
        ),
        migrations.AlterField(
            model_name='rateplan',
            name='hs_plan',
            field=models.IntegerField(choices=[('0', '未加入'), ('1', 'プラチナ年払い'), ('2', 'スタンダード年払い'), ('3', 'プラチナ月払い'), ('4', 'スタンダード月払い')], default=0, verbose_name='ほっとサポート'),
        ),
        migrations.AlterField(
            model_name='rateplan',
            name='insurance_descount',
            field=models.BooleanField(default=False, help_text='多頭割の場合のみチェック', verbose_name='保険多頭割'),
        ),
        migrations.AlterField(
            model_name='rateplan',
            name='insurance_plan',
            field=models.IntegerField(choices=[('0', '未加入'), ('1', '100%年払い'), ('2', '70%年払い'), ('3', '100%月払い'), ('4', '70%月払い')], default=0, verbose_name='ペット保険'),
        ),
        migrations.AlterField(
            model_name='rateplan',
            name='pet_price',
            field=models.IntegerField(help_text='*税込み金額/半角数字で入力', verbose_name='ペット代金'),
        ),
    ]
