# Generated by Django 2.2.4 on 2019-10-03 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191003_1724'),
    ]

    operations = [
        migrations.AddField(
            model_name='rateplan',
            name='loan_company',
            field=models.IntegerField(choices=[(0, '一括'), (1, 'PFクレジット'), (2, 'アプラス'), (3, 'PFS'), (4, 'FLEX'), (5, 'セディナ'), (6, '西京カード'), (7, 'シティックス')], default=1, verbose_name='支払方法'),
        ),
    ]
