# Generated by Django 2.2.4 on 2019-10-03 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20191003_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rateplan',
            old_name='other',
            new_name='other_price',
        ),
    ]
