# Generated by Django 2.2.4 on 2019-10-03 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20191003_1917'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rateplan',
            old_name='insurance_descount',
            new_name='insurance_discount',
        ),
    ]
