# Generated by Django 2.2.4 on 2019-10-04 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20191004_0136'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=20, verbose_name='ローン会社')),
            ],
        ),
        migrations.AddField(
            model_name='rateplan',
            name='bonus_payment',
            field=models.IntegerField(default=0, help_text='1000円単位で入力', verbose_name='ボーナス加算額'),
        ),
        migrations.AddField(
            model_name='rateplan',
            name='bonus_s_month',
            field=models.IntegerField(choices=[(6, '6月'), (7, '7月'), (8, '8月')], default=6, verbose_name='ボーナス月（夏）'),
        ),
        migrations.AddField(
            model_name='rateplan',
            name='bonus_setting',
            field=models.BooleanField(default=False, help_text='ボーナス支払を設定する場合はチェック', verbose_name='ボーナス支払設定'),
        ),
        migrations.AddField(
            model_name='rateplan',
            name='bonus_w_month',
            field=models.IntegerField(choices=[(12, '12月'), (1, '1月')], default=12, verbose_name='ボーナス月（冬）'),
        ),
        migrations.AddField(
            model_name='rateplan',
            name='down_payment',
            field=models.IntegerField(default=0, verbose_name='頭金'),
        ),
    ]
