# Generated by Django 2.2.4 on 2019-10-04 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20191004_1251'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LoanCompany',
        ),
        migrations.AlterField(
            model_name='rateplan',
            name='bonus_payment',
            field=models.IntegerField(default=0, help_text='*1000円単位で入力', verbose_name='ボーナス加算額'),
        ),
        migrations.AlterField(
            model_name='rateplan',
            name='bonus_setting',
            field=models.BooleanField(default=False, help_text='*ボーナス支払を設定する場合はチェック', verbose_name='ボーナス支払設定'),
        ),
        migrations.AlterField(
            model_name='rateplan',
            name='loan_company',
            field=models.IntegerField(choices=[(0, '一括'), (1, 'PFクレジット'), (2, 'アプラス①'), (3, 'アプラス②'), (4, 'アプラス③'), (5, 'PFS'), (6, 'FLEX'), (7, 'セディナ'), (8, '西京カード'), (9, 'シティックス')], default=2, verbose_name='支払方法'),
        ),
    ]
