# Generated by Django 2.2.4 on 2019-10-05 02:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20191005_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='rateplan',
            name='created_at',
            field=models.DateField(default=datetime.date.today, verbose_name='作成日'),
        ),
    ]
