# Generated by Django 2.2.4 on 2019-10-05 18:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0011_rateplan_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='rateplan',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作成者'),
            preserve_default=False,
        ),
    ]
